### ISSUE TITLE
config/routes.rb file defines /users/new twice

### ISSUE THREAD

**Issue by christinalcole** [learn-co-curriculum/has_secure_password_lab#10]
@Lukeghenco: as mentioned, the /users/new route is defined twice in the solution branch, once as `get '/users/new'` (line 2) and again as `resources :user` (line 8).  Since the lab's README specs that the UsersController should response to #new and #create actions, would it make sense to remove line 2, revise line 8 to `resources :user, only: [:new, :create]`?

**Comment by gj** [comment]
Thanks @christinalcole !
