### ISSUE TITLE
users_controller_spec.rb expecting redirect_to may be bad practice

### ISSUE THREAD

**Issue by BebopVinh** [learn-co-curriculum/has_secure_password_lab#13]
```
 it "redirects you if your password and confirmation don't match" do
      typo = steven.merge(password_confirmation: 'uni111verse')
      post :create, params: { user: typo }
      expect(response).to redirect_to(controller: 'users', action: 'new')
 end
```

We should be able to use `render :new`, that way the user's name is still pre-fill in the text field. However, the test is expecting us to use `redirect_to`

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
