### ISSUE TITLE
This lab is still broken

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/has_secure_password_lab#7]
The learn open link still does not work for this lab, and the only repository available has all of the solutions.

**Comment by AnnJohn** [comment]
sorry about that @Lukeghenco. will look into this soon.

**Comment by AnnJohn** [comment]
hi @Lukeghenco can you check to see if it's working now?

**Comment by Lukeghenco** [comment]
I am able to fork and clone it now, but I am still unable to get learn to realize my tests are passing

**Comment by Lukeghenco** [comment]
Ok I deleted all of my old repositories and local repos, and I am getting it to work now. Thanks

**Comment by AnnJohn** [comment]
great, thank you.
